import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.css'
import NavBar from '../components/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.wrapper}>
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  )
}
